### ISSUE TITLE
Version missmatch on typescript linked-list

### ISSUE THREAD

**Issue by ntijoh-Alexander-Fransson** [exercism/ruby-test-runner#64]
Tests got green localy but not on the website. The testbot gave me this message "The submitted code didn't compile. We have collected the errors encountered during compilation. At this moment the error messages are not very read-friendly, but it's a start. We are working on a more helpful output.
-------------------------------
linked-list.ts(71,13): error TS2367: This condition will always return 'true' since the types 'Node<T>' and 'T' have no overlap."

**Comment by kotp** [comment]
Are you positive this happened on the Ruby Track?

**Comment by kotp** [comment]
Closing for no confirmation/no response, and no other reports of this nature.
